# Backend
backend = "glx";

# Required when a shader makes opaque pixels transparent
force-win-blend = true;

# Background blur
blur-method = "dual_kawase";
blur-strength = 2;

# Apply the color-transparency shader to the applications
# you want to use this effect on.
window-shader-fg-rule = [
	"translucent-colors.frag:class_g = 'Thorium-browser' && name *= 'ChatGPT'",
	"translucent-colors.frag:class_g = 'Xfce4-terminal'",
	"translucent-colors.frag:class_g = 'code'",
	"translucent-colors.frag:name = 'yt-x'",
	"translucent-colors.frag:class_g = 'Thunar'",
	"translucent-colors.frag:class_g = 'Tk' && name *= 'Timer'"
];

# Window opacity
opacity-rule = [
	"75:class_g = 'Thorium-browser' && name *= 'ChatGPT'",
	"75:class_g = 'Xfce4-terminal'",
	"75:class_g = 'code'",
	"85:name = 'yt-x'",
	"75:class_g = 'Thunar'",
	"50:class_g = 'Tk' && name *= 'Timer'"
];
